### ISSUE TITLE
Transformers to 2.4/2.5

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#1001]
- Revisit major new Transformers features—consider adopting their methods for checkpointing etc. if there's a clear advantage.
- In any case, update the required package version, and make sure it runs with both current and new pre-trained models.

**Comment by zphang** [comment]
To add urgency to this, XLM-RoBERTa is basically broken in v2.3.0. It cannot be loaded at all because of an issue in the tokenizer vocabulary (core dump due to a bad vocabulary lookup, because of an issue with vocab size). 

See: https://github.com/huggingface/transformers/pull/3014#pullrequestreview-364379645 for more details

We will likely want to update to at least v2.5.1 (v2.5.0 seems to have its own set of issues).

**Comment by pyeres** [comment]
Addressed by @zphang's PR (https://github.com/nyu-mll/jiant/pull/1059) which updated dependency to Transformers version 2.6.0.
