### ISSUE TITLE
Extend max_seq_len truncation strategies

### ISSUE THREAD

**Issue by pyeres** [nyu-mll/jiant#1009]
PR #1006 introduced the option to provide truncation strategies during `apply_boundary_tokens`. This issue captures requests/TODOs for enhancements:

* extend `apply_boundary_tokens` to accept an arbitrary number of input sequences (`sn`)
* extend `_apply_boundary_tokens_with_trunc_strategy` wrapper to specify truncation strategies for an arbitrary number of input sequences
* update `AlphaNLITask` to apply trunc strategies, e.g., `boundary_token_fn(s1=obs1, s2=hyp, s3=obs2, trunc_strategy...)`

**Comment by pyeres** [comment]
@zphang for visibility as contributor of related task (`AlphaNLITask`).

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1009.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
