### ISSUE TITLE
Using different datasets fro probing tasks

### ISSUE THREAD

**Issue by mahsash** [nyu-mll/jiant#1010]
Hi.

As I do not have access to Ontonotes dataset, I tried to reproduce results for NER probing task using a different NER dataset. I changed its format to the one you use for probing tasks and replaced the rel_path in edges-ner-ontonotes task with the address to point to where I saved my dataset (after retokenizing and populating it with labels.txt file). 
But when I run it I get following error:
"RuntimeError: No dimension to distribute: torch.Size([768])"

This is an example from my train.json file:
{"text": "The Commonwealth Bank Tennis Classic is a tennis tournament on the WTA Tour held in Bali , Indonesia .", "targets": [{"span1": [1, 5], "label": "I-MISC"}, {"span1": [11, 12], "label": "I-ORG"}, {"span1": [15, 16], "label": "I-LOC"}, {"span1": [17, 18], "label": "I-LOC"}]}

Can you help me to resolve this error?

**Comment by sleepinyourhat** [comment]
@iftenney - Mind giving this a first look?

**Comment by mahsash** [comment]
Hi again.

I also ran it with seminal data for relation classification task and got the same error. Can you please help me? I am in a hurry.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1010.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
