### ISSUE TITLE
Missing data preprocessing dependency for JOCI Task

### ISSUE THREAD

**Issue by pyeres** [nyu-mll/jiant#1020]
`jiant`'s `JOCI` task implementation depends on `train.tsv`, `dev.tsv`, and `test.tsv` files. These files appear to be versions of the [JOCI data set](https://github.com/sheng-z/JOCI/tree/master/data). To make this task fully reproducible in `jiant` we should bring in any code necessary to transform the original data into the version used by `jiant`.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1020.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
