### ISSUE TITLE
Performance issues on broadcoverage- and glue-diagnostic tasks

### ISSUE THREAD

**Issue by pyeres** [nyu-mll/jiant#1021]
Recent [benchmarking experiments](https://github.com/nyu-mll/jiant/pull/992#issuecomment-588256306) showed reduced performance on some diagnostic tasks.

**Comment by sleepinyourhat** [comment]
Do we have any evidence of when these regressions started?

**Comment by pyeres** [comment]
> Do we have any evidence of when these regressions started?

Kicking off some runs to narrow this down:
1. Re-running experiments using RoBERTa under 1.2.1.
2. Checking BERT-large performance on the same tasks under 1.3.0, 1.2.1, and 1.1.0.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1021.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
