### ISSUE TITLE
Phasing out ELMo support

### ISSUE THREAD

**Issue by pyeres** [nyu-mll/jiant#1026]
Phasing out ELMo support has been floated in recent `jiant` roadmap planning meetings. 

This issue tracks ongoing conversations around phasing out ELMo support.

**Comment by iftenney** [comment]
FWIW, there are still some excellent papers (e.g. https://arxiv.org/abs/2003.12298) that are using ELMo in jiant!

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1026.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
