### ISSUE TITLE
Break up `models.py`

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#1033]
Our rough abstraction for jiant models is shared components (embedding layer + phrase layer / sentence encoder) and task-specific components. Currently, the definitions, constructors, and function calls for *all* models is in `models.py`, making it difficult and intimidating to read and modify. One way to break up this file is moving all the embedding layer stuff in one file, all the task specific stuff in one file, etc., though the exact organization is TBD.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1033.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
