### ISSUE TITLE
Fold RNNs, BoW into non-contextual word embeddings

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#1034]
There was discussion of merging non-null phrase layers into non-contexual word embeddings, as most of the time, we are not combining these phrase layers with contextual word embeddings (BERT, GPT, etc.). This would simplify the complexity of `models.py` and go hand-in-hand with #1033.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1034.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
