### ISSUE TITLE
Refactor load_tsv

### ISSUE THREAD

**Issue by pyeres** [nyu-mll/jiant#1040]
`jiant`'s [adding tasks](https://github.com/nyu-mll/jiant/blob/master/tutorials/adding_tasks.md) walkthrough recommends implementing `load_data()` using [`load_tsv()`](https://github.com/nyu-mll/jiant/blob/61440732f4df2c54e68e59ead34b8656bf52af3b/jiant/utils/data_loaders.py#L79-L199).

[`load_tsv()`](https://github.com/nyu-mll/jiant/blob/61440732f4df2c54e68e59ead34b8656bf52af3b/jiant/utils/data_loaders.py#L79-L199) has many responsibilities and conditional pathways and limited tests. This makes adding tasks more difficult, and increases the risk that changes (silently) break other tasks' loaders.

Suggestions:
1. remove the suggestion to use [`load_tsv()`](https://github.com/nyu-mll/jiant/blob/61440732f4df2c54e68e59ead34b8656bf52af3b/jiant/utils/data_loaders.py#L79-L199) from [adding_tasks.md](https://github.com/nyu-mll/jiant/blob/master/tutorials/adding_tasks.md)
2. refactor existing tasks to remove dependencies on [`load_tsv()`](https://github.com/nyu-mll/jiant/blob/61440732f4df2c54e68e59ead34b8656bf52af3b/jiant/utils/data_loaders.py#L79-L199) (example in PR #1039)

Marked as related to Issue #886.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1040.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
