### ISSUE TITLE
Apply Black formatting to files last modified before Black requirement

### ISSUE THREAD

**Issue by pyeres** [nyu-mll/jiant#1044]
Black formatting is enforced on all new file modifications, but there are a number of files that were last modified before Black requirements were put in place. When changes are made to these files automatic Black formatting reformats the file sometimes contributing lots of unrelated formatting changes to the intended changes.

Recommendation: apply Black reformatting project-wide in a (non-feature) PR.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1044.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
