### ISSUE TITLE
Word Embeddings for BLiMP testing

### ISSUE THREAD

**Issue by MikeinBoulder** [nyu-mll/jiant#1045]
I'm trying to understand and reproduce the tests in the current BLiMP model so that we can build a Spanish language version.  I've followed the instructions in the ReadMe for installing JIANT and for running the Blimp scripts but I get the following error:
        Cannot resolve variable ${WORD_EMBS_FILE}

Is there a particular word embedding model required to run these BLiMP scripts?  Should I use GLoVE?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1045.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
