### ISSUE TITLE
Apex / FP16 support

### ISSUE THREAD

**Issue by timhartill** [nyu-mll/jiant#1048]
setup_tutorial.md mentions setting up Apex for FP16 support however there doesn't currently seem to be any parameter in the configuration that can enable it and the code doesn't currently seem to utilise apex. I was wondering whether there was active work in progress to enable this feature and if so what the likely timeline for a release might be?

**Comment by sleepinyourhat** [comment]
@HaokunLiu - Have you had any luck using Apex FP16?

**Comment by HaokunLiu** [comment]
Currently it’s not supported. It might be a miscommunication that some of
us put that in the readme.

For now, please ignore it.

FWIW, I opened a PR to support FP16 , but it’s not in my recent priorities.
If you are still using jiant two months later, we probably will have FP16.

**Comment by timhartill** [comment]
Thanks for your response and I'm sure I will be using this great tool for some time to come.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1048.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
