### ISSUE TITLE
analyzing the data after probing

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1054]
Hello,
I got a little lost in how to analyze the data received after probing.
So I did the whole probing proccess and would like to analyze the data saved under $JIANT_PROJECT_PREFIX.
I saw in the README file located in the probing directory that there are files dedicated for this purpose, like "analysis.py", "analyze_runs.py" and so on, but I didn't understand how to use them exactly.
If anyone could guide me as to how to use these scripts, or any other way, to analyze the data received from the probing process, I would be very grateful.
Thanks!

**Comment by sleepinyourhat** [comment]
@iftenney

**Comment by iftenney** [comment]
What kind of analysis are you aiming to do?

`analyze_runs.py` is probably the simplest entry-point; see the docstring in that file for usage. The output is a tsv file containing a number of metrics.

**Comment by iftenney** [comment]
There's a bit more documentation on the analysis code and output format here: https://github.com/nyu-mll/jiant/tree/master/probing#getting-started

FWIW, depending on your use-case it may be easier to just read the predictions JSON directly and compute the metrics you need. 

(The main reason for the `analyze_runs.py` script was that parsing JSON is slow, so for the large number of runs from the paper it was easier to have an "offline" scoring script rather than doing everything from Jupyter notebooks.)
