### ISSUE TITLE
Speculative: Add support for automatic early stopping of poor runs

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#1055]
Inspired by: https://arxiv.org/abs/2002.06305

Minimally: End training if a certain target accuracy isn't reached by some (early-ish) number of steps. This can be set manually to automatically catch jobs that fail due to a poor random seed.

Ideally: Integrate with some kind of experiment manager for hyperparameter tuning, so as to kill jobs that perform well below average early in tuning.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1055.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
