### ISSUE TITLE
Decouple evaluation tasks from target tasks

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#1056]
Right now, target tasks are tightly coupled with evaluation tasks (for example, all target tasks are evaluation tasks). If we want to train on Task B, and then evaluate on a separate task (say Task A) that was not trained on, the closest way to do so is to add Task A to the list of ALL_DIAGNOSTICS tasks in tasks/__init__, add Task A as a pretraining task (because it seems as though target task training does not filter for ALL_DIAGNOSTICS), and then specify use_classiifer in the config to be Task B. 
This is very convoluted and unintuitive. Instead, an easy-ish fix would be to just add an evaluation_tasks list. We might have to keep the use_classifier config parameter, or figure out another way to indicate which model to use in the evaluation of an evaluation task.

**Comment by sleepinyourhat** [comment]
I agree that this isn't super intuitive. How would evaluation_tasks work? I could imagine defaults for that being both confusing and important.

Another hacky workaround: Run jiant twice, once for target training only, and a second time for evaluation.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1056.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
