### ISSUE TITLE
zero-shot

### ISSUE THREAD

**Issue by pasinit** [nyu-mll/jiant#1068]
Dear all, 
I was wondering if there is a way to train a model on a task and then test on multiple target task without doing any additional training on each of them nor having dedicated parameters in the models for those tasks. IN other words, is it possible to have a zero-shot setting where one train on a dataset in one language and test in other languages without performing training on each of them?

Thanks

**Comment by pruksmhc** [comment]
There is a way to accomplish this in jiant, but it is not very intuitive - that is currently what we do with the diagnostic tasks in this repo. Here's a thread about it. 
https://github.com/nyu-mll/jiant/issues/1056
In terms of testing in other languages, right now, we only support English-language tasks. You would have to add tasks with datasets in other tasks. Please refer to our tutorial on adding tasks: https://github.com/nyu-mll/jiant/blob/master/tutorials/adding_tasks.md

**Comment by pasinit** [comment]
thanks :)

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1068.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
