### ISSUE TITLE
MultiRC task- v1.0 results are better than v1.3 (Unknown reason, after reviewing changes)

### ISSUE THREAD

**Issue by varunchaudharycs** [nyu-mll/jiant#1081]
Hi,
I'm trying out the MultiRC dataset task(Khasabi et. al 2018). Using the two jiant versions gave the following F1 scores(using BERT-base):
**jiant v1.3  = ~58**
**jiant v1.0 = ~65**
with both having the same configurations. I looked over the changes and found one:
v1.0 gives (para + ques + ans option) as BERT input
v1.3 gives ([CLS] para [SEP] ques + ans option [SEP]) as BERT input

I tried doing the same thing as v1.0 in v1.3 but observed no changes in the F1 score(rather F1 decreased).

Kindly let me know if I may try out some other changes between the two versions that I have missed earlier. This drastic drop in performance over version upgrade is hard to understand.

**Comment by W4ngatang** [comment]
Hey Varun,

Sorry to hear that. So we have more info, can you share your config file? Also, has the drop been consistent across random seeds before and after the version change?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1081.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
