### ISSUE TITLE
reproducing the expected layer results of the paper

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1084]
Hey,
I've been trying to reproduce the expected layer results of the "BERT Rediscovers the Classical NLP Pipeline" paper for the coreference problem (meaning I wanted to get the 9.47 result for the expected layer of the coreference problem).
I've tried to extract the F1 using the "Edge Probing Predictions Sandbox" example analysis code, and then calculate the expected layer using the equation in the paper.
Nevertheless, I keep getting 3.05 for the expected layer, rather than the 9.47, and I'm trying to understand what am I doing wrong.
I've included the code here - does anyone see anything that I'm doing wrong?
I suspect it's got something to do with me taking the long data, but I've tried it with the wide data and got 2.47 for the expected layer.
Here's the code:
``
import sys, os, re, json
import itertools
import collections
import matplotlib.pyplot as plt
from importlib import reload
import pandas as pd
import numpy as np
from sklearn import metrics

BERT_LAYERS=12

import analysis
reload(analysis)

# getting preds for all layers
preds_dict = dict()
score_dict = dict()
score_dict_long = dict()
for i in list(range(BERT_LAYERS + 1)):
    run_dir = "/cs/labs/oabend/lovodkin93/jiant_rep/jiant_outputs/bert-base-uncased-mix_" + str(i) + "-edges-coref-ontonotes/run"
    preds = analysis.Predictions.from_run(run_dir, 'edges-coref-ontonotes', 'test')
    preds_dict[f'layer_{i}'] = preds
# calculating long F1 for all layers
for i, layer in enumerate(preds_dict):
    preds= preds_dict[layer]
    long_df = preds.target_df_long
    score_dict_long[layer] = metrics.f1_score(y_true=long_df['label.true'], y_pred=(long_df['preds.proba'] >= 0.5))
# calculating the expected layer
prev_score = score_dict_long["layer_0"]
numerator = 0
denominator = 0
for i, layer in enumerate(score_dict_long):
    if (i==0):
        continue
    curr_score = score_dict_long[layer]
    delta = curr_score - prev_score
    numerator = numerator + (i*delta)
    denominator = denominator + delta
    prev_score = curr_score
exp_layer = numerator/denominator
print("expected layer is : " + str(exp_layer))
``

**Comment by iftenney** [comment]
It's a bit hard to debug without access to the data, but can you plot the F1 score from each layer, as well as the deltas? Does it look at all like the purple bars in Figure 2?

**Comment by iftenney** [comment]
Ahh - nevermind, it looks like you're using BERT base? The 9.47 number is from BERT large which is twice as deep. There are numbers and plots for BERT base in the appendix, for coref we got 3.62 from cumulative scoring. 

I think the remaining difference might be because coref is a binary task but the code implements it as two targets '0' and '1', so for scoring we only look at the '1' label. See this notebook: https://github.com/nyu-mll/jiant/blob/master/probing/analysis_edgeprobe_ICLR_camera_ready.ipynb (Ctrl+F for `is_coref_task`)

As a sanity check, you could look at the F1 score from the full model (mix over layers 0-12), and that should match the numbers in Figure A.2

**Comment by lovodkin93** [comment]
amazing! thank you!
Also, is the expected layer calculated based on the F1 results of the test set or the val set?

**Comment by lovodkin93** [comment]
yup, that did the job.
Thank you very much!
