### ISSUE TITLE
Add a warning in the defaults.conf for BERTAdam, and remove it as a default from all scripts

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#1096]
BERTAdam considered harmful in fine-tuning:

https://arxiv.org/abs/2006.05987
https://arxiv.org/abs/2006.04884

In the spirit of Reasonable Defaults:
- Add a warning in the defaults.conf where BERTAdam is mentioned
- Remove it as a default from all example scripts
- Make sure that our support for conventional Adam is working, and use it as the replacement

(Relevant to @claravania)

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1096.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
