### ISSUE TITLE
support languages other than English 

### ISSUE THREAD

**Issue by ssabzzz** [nyu-mll/jiant#1098]
I want to use a multilingual BERT model which apparently is not an option in jiant. (my test dataset is not in english)

Is there a way to achieve this right now?

**Comment by sleepinyourhat** [comment]
I believe there aren't any firm obstacles to setting up XLM-R support or non-English tasks. This isn't trivial, but if you can identify all of the RoBERTa-specific code, you should be able to set up a parallel code path for XLM-R.

Alternately, we're finishing up the initial draft/beta release of jiant 2, which will be public in about two weeks. That will have a somewhat different interface, but it will almost certainly support XLM-R from the start.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1098.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
