### ISSUE TITLE
ImportError: cannot import name 'Ontonotes' from 'allennlp.data.dataset_readers.dataset_utils'

### ISSUE THREAD

**Issue by csyhhu** [nyu-mll/jiant#1105]
Hi !

I try to download and extract ontonotes data using `get_and_process_all_data.sh`, and it comes out with the error as : 

> ImportError: cannot import name 'Ontonotes' from 'allennlp.data.dataset_readers.dataset_utils'

I have checked `allennlp.data.dataset_readers.dataset_utils`, indeed there is no Ontonotes. And I look back to `allennlp` to search `Ontonotes`, the only result is shown here: https://github.com/allenai/allennlp/blob/c4c532d25e012dbe6ab1ac14bca75e53e0acc621/scripts/compile_coref_data.sh

without any classes named as `Ontonotes`.

Here is my version:
allennlp==1.1.0rc2.dev20200724
allennlp-models==1.1.0rc2.dev20200724

Or should I follow the instruction in README.md to use `extract_ontonotes_all.py` to process the ontonotes datasets?

Best regards

**Comment by sleepinyourhat** [comment]
Hrm—I don't know that part of the code well. @HaokunLiu @zphang, any guess?

**Comment by sagnik** [comment]
This is pretty late, but I think this is because of a version mismatch. `enviornment.yml` specifies the `allennlp` version to be `0.8.4`. I think if you create a `jiant` environment using `conda create -f environment.yml` it would pull down the proper version of AllenNLP and things would work.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1105.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
