### ISSUE TITLE
acquiring data on the lengths of spans

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1111]
Hello, So I've been working with your project for a while now.
I've mostly worked on the Coreference and the SRL tasks, both of which have 2 spans, and I was analyzing the impact of the distance between these spans. For that, I've been using the "stratisfier"'s column in the dataframe acquired from the Ontonotes dataset (using the tsv file generated by the "analyze_runs.py file that is located in the probing firectory) . Recently, I have also wanted to examine the impact of the length of the spans in the NER task, but I can't seem to find how to get that information from the tsv file generated by thr "analyze_runs.pu file. 
Does anyone happen to know how I can acquire that information?
Thanks!

**Comment by iftenney** [comment]
Hi,

I don't think the span length is output by default, but you could add a couple lines to compute it in `analysis.py`:
- Add something here to add it to the DataFrame: https://github.com/nyu-mll/jiant/blob/master/probing/analysis.py#L407
- Add the column name to this list so it will stratify metrics: https://github.com/nyu-mll/jiant/blob/master/probing/analysis.py#L493

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1111.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
