### ISSUE TITLE
How to get the JSON files for SPR1 and 2?

### ISSUE THREAD

**Issue by sagnik** [nyu-mll/jiant#1113]
[SPR processing script](https://github.com/nyu-mll/jiant/blob/master/probing/data/convert-spr1-rudinger.py) requires the SPR data in JSON format. Any idea from where to get that? The only place I can find is [dcomp.io](http://decomp.io/data/) and the formats don't match and the code specifically mentions about JSON files being easier than the other format.

**Comment by sleepinyourhat** [comment]
@iftenney 

(Alternately, we have rebuilt-from-scratch support for Edge Probing in v2 alpha, with a more active development/support team: https://github.com/jiant-dev/jiant - It'll be out in a full release in a couple of weeks.)

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1113.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
