### ISSUE TITLE
Is squad task implemented? 

### ISSUE THREAD

**Issue by sagnik** [nyu-mll/jiant#1114]
First of all, truly awesome work! I have just started to explore it and absolutely love it. I have a couple of questions:

1. From the Jiant paper, seems `squad`  task is implemented:
![image](https://user-images.githubusercontent.com/4563472/93379431-1ddf2900-f85e-11ea-99c5-0c0375aa6630.png)
But I can't seem to find it in `tasks.py` (at least on the `dev` branch). Is it implemented on some other branch?

2. Is there a slack channel/gitter chat/stackoverflow tag where I can ask trivial questions like this issue and issue #1113? They are not quite _issues_ so I think they would be better placed somewhere else.

**Comment by sleepinyourhat** [comment]
SQuAD: @zphang Do you there's a v1 branch with SQuAD support? Sadly, I fear that that reference may have been only to v2 alpha (https://github.com/jiant-dev/jiant), which definitely does support SQuAD. v2 will be out as a full release within a couple of weeks, though the interface is quite distinct from what you see here now.

Questions: Sadly, no. (Though this isn't a bad idea; @zphang @jeswan.) This is the right place for these questions.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1114.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
