### ISSUE TITLE
span_distance results

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1116]
I was going through the span_distance success rate and couldn't figure out according to which label it is calculated.
So my question is this: are the success rates of the span_distances calculated similarly to the choice of metric/label of the specific task that is used to calculate the expected layer (for example for the coreference - label='0', for the srl - label = '_clean_micro_', etc.)?

**Comment by sleepinyourhat** [comment]
It looks like this is about code in the `probing/` directory—paging @iftenney.

**Comment by iftenney** [comment]
For figure 3 of the paper, we just used the full micro F1 score since there isn't any additional filtering for the dependency task. I think you may need to do additional filtering in analysis.py (e.g. https://github.com/nyu-mll/jiant/blob/master/probing/analysis.py#L493) if you wanted to restrict to certain classes as well.

**Comment by lovodkin93** [comment]
> For figure 3 of the paper, we just used the full micro F1 score since there isn't any additional filtering for the dependency task. I think you may need to do additional filtering in analysis.py (e.g. https://github.com/nyu-mll/jiant/blob/master/probing/analysis.py#L493) if you wanted to restrict to certain classes as well.
> 
> (Sorry for the delay - I've been out of office the past week.)

First of all thank you for youe reply!
Second of all, I don't think there is any reference to the span distance in the paper. Basically,  in my work, I'm trying to calculate the expected layers for instances of spans with certain distance between them. Therefore, I want to use the equation of the expected layer, that requires for me to use the scores for those distances. I want to compare those results to the expected layer of all the examples (which is mentioned in your article), and that is why I want to know whether in both cases the same success rate is used.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1116.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
