### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/cs/labs/oabend/lovodkin93/jiant_rep/jiant-ep_frozen_20190723/data/edges/ontonotes/coref/labels.txt'

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1117]
After I ran the probing/data/extract_ontonotes_all.py, like in the example in probing/data/README.md, and it generated the relevant json files in data/edges/ontonotes, I then proceeded to run the following prompt command: 
bert_mix_k_exp edges-coref-ontonotes base-uncased 0
similarly to the example in probing/README.md and based on https://github.com/nyu-mll/jiant/blob/master/scripts/edgeprobing/exp_fns.sh#L191, and I received the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/cs/labs/oabend/lovodkin93/jiant_rep/jiant-ep_frozen_20190723/data/edges/ontonotes/coref/labels.txt'

I assume this label.txt file should have been generated during extract_ontonotes_all.py's run, but it hasn't. Has anyone encountered this problem?
Thanks!

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1117.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
