### ISSUE TITLE
srl success rate

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1124]
Hello,
I've been going through the code, and I found in https://github.com/nyu-mll/jiant/blob/master/probing/analysis_bertlayer_ACL_camera_ready.ipynb that the success rate used for the srl task is _clean_micro_. But, when I processed the data, in accordance with https://github.com/nyu-mll/jiant/tree/master/probing, the dataframe of the srl results didn't have any _clean_micro_ label, only _macro_avg_ and _micro_avg_. Is there something specific that needs to be done to acquire also the _clean_micro_ label? Or rather, is there a different success rate used for the calculations of the srl's expected layer (2.59 according to the paper).
Thank you!

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1124.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
