### ISSUE TITLE
problem when runing examples

### ISSUE THREAD

**Issue by YoungTimmy** [nyu-mll/jiant#1248]
hi all, I am tring to run single-task Traing, following the instructions in examples.
However, I have met the baffling problems. 
Just as the picture shows: first the script causes a **PermissionError: [Errno 13] Permission denied: '/content'**,
after I add **sudo**, it changes to **SyntaxError: invalid syntax**. The code is clean and my python version is 3.7.9, so I do not know why. 
By the way, doesn't _**jiant**_ support python 3.9? when I tried to install with python 3.9, it also cause so many errors.

Anyone could help, thanks a lot!

![problem1](https://user-images.githubusercontent.com/39907234/102715608-93510e80-4311-11eb-9866-6c26800e7aab.png)
![after-sudo](https://user-images.githubusercontent.com/39907234/102715613-96e49580-4311-11eb-84f8-c2eddd6ede69.png)

**Comment by jeswan** [comment]
The `output_path` should be the absolute file path of where you want to store the task data. Since the examples are for Colab notebooks, `/content/tasks/` is a valid directory in this environment. When running locally, you must specify a valid path for downloaded task data (ie: /Users/$USER/task_data). I don't understand the intention of using `sudo` in this context. Adding `jiant` to PYTHONPATH enables you to import `jiant` in your Python env.

**Comment by YoungTimmy** [comment]
thank you！ the problem is solved
