### ISSUE TITLE
clear task scorers before evaluating / validating

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#185]
Before validating or evaluation, we should reset each task's scorers to ensure we're validating on just the data from the split. This will likely causes division by zero errors we'll need to catch.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/185.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
