### ISSUE TITLE
Evaluating on MNLI-diagnostic alone fails

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#224]
eval_tasks = mnli-diagnostic, train_tasks = none
...
AttributeError: 'MultiTaskModel' object has no attribute 'mnli_mdl'

If anyone sees easy logic to add to make sure that we create an MNLI model when this task is requested, would be worth adding.

**Comment by sleepinyourhat** [comment]
@zphang Mind taking a look at this, since you're working with related code?

**Comment by zphang** [comment]
Looked into this.

It looks like one issue is that to build the corresponding task module requires instantiating the Task object, which requires loading the corresponding task data (that we don't need) along the way. If we're fine with this compromise, this is an easy fix. Otherwise, we need to add functionality to building out the module without the Task object, or building a skeleton Task object without loading the data.

Relatedly, there is some similar logic in https://github.com/nyu-mll/jiant/blob/master/src/models.py#L411-L419 for generating tasks based on the use_classifier overrides, which also highlights the issue of reloading MNLI data.

**Comment by sleepinyourhat** [comment]
Hrm—this could turn out to be a problem in the future for very data-rich tasks like MLM. How easy would it be to have an option in the task object init code to prevent any data from being loaded?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/224.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
