### ISSUE TITLE
rename config args (task_patience, elmo/elmo_chars_only/training stage names)

### ISSUE THREAD

**Issue by pitrack** [nyu-mll/jiant#315]
* `task_patience` is misleading, `lr_patience` would be a better name

* "no elmo" (as we report) is not actually `elmo = 0` -- this is a bit counterintuitive too.

* names of training stages (see comment below)

**Comment by shuningjin** [comment]
I may help with this. 

Is just changing the following names in configs, trainer.py, main.py:
# patience
task_patience -> lr_patience
# training stage
do_train-> do_pretrain
train_for_eval -> train_target_tasks
do_eval -> do_eval_only
train_tasks -> pretrain_tasks
eval_tasks -> target_tasks
(not sure what to do with elmo though, current setting seems make clear.)

**Comment by pitrack** [comment]
Agreed that current elmo settings make enough sense, especially with current documentation.

I'm a bit worried about making this change without messing up loading/restoring existing runs but I think it'd be a good thing in the long run, especially if nobody is actively working on loading/restoring runs?

**Comment by sleepinyourhat** [comment]
Saving/restoring shouldn't be too bad—it'll only impact the saved params files, and I don't think those are too heavily used. None of this goes into the model state files. Plus, our experiments are happening on a frozen branch.

So, Shuning, go for it! Thanks!

Suggestions:

train_for_eval -> do_target_task_training (for parallelism)
do_eval -> do_full_eval (It's not eval _only_ since you can combine this with other flags. My suggested name might help remind people that the evals done during target task training are incomplete, which is easy to forget.)

**Comment by iftenney** [comment]
@epavlick are you using saved params files for any NLI probing experiments?

It might be worth making a script to convert old param files by doing this remapping, just in case we want to do probing on older models.

**Comment by pruksmhc** [comment]
@iftenney  this looks pretty much solved - can be closed?

**Comment by sleepinyourhat** [comment]
@iftenney

**Comment by sleepinyourhat** [comment]
All either solved or covered in #557.
