### ISSUE TITLE
Test set performance regression - possible write_preds bug?

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#341]
Looking into this.

**Comment by sleepinyourhat** [comment]
We're _still_ getting some suspicious behavior. We just evaluated two of our best paper runs, and they're around 67 and 70—not terrible, but lower than some of our earlier runs that did worse on dev.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/341.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
