### ISSUE TITLE
preprocess.py cleanup

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#374]
preprocess.py has a few open TODOs for speed and readability improvements.

```
  156:     TODO(iftenney): multiprocess the $%^& out of this.
  207:         # TODO: remove this case and stream everything.
  367:         # TODO: delete task.{split}_data_text as well?
  479:                 # TODO: remove special case, replace with something general
```

**Comment by sleepinyourhat** [comment]
@iftenney - Any conclusions?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/374.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
