### ISSUE TITLE
Vocabularies that need to be constructed will be skipped if there is a vocab folder in exp_dir

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#401]
Example: I train on some GLUE tasks from scratch, creating a vocab folder with a char and word vocab.
I then train a WMT task using the same exp dir. Since a vocab object already exists, we skip creation of the WMT-specific vocabulary, and all your data is mapped to 1s (<UNK>s). Doubly bad: there will be no warning or indication that your data is getting screwed.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/401.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
