### ISSUE TITLE
Add QA-NLI as a pretraining task

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#418]
Stanford's new QA-NLI dataset follows the same basic idea as QNLI, but it fits the NLI definition more closely, and it's drawn from more than just SQuAD. It could be interesting to try to for pretraining.

https://arxiv.org/pdf/1809.02922.pdf
https://worksheets.codalab.org/worksheets/0xd4ebc52cebb84130a07cbfe81597aaf0/

Complications:
- The dataset isn't actually set up for NLI classification yet—there's no label field. The paper discusses positive and negative examples, and I assume that they can be derived from the data in some way, possibly by cross-indexing with the original QA datasets... We may need to contact the authors.
- To run on the test set, we'd need to package our code for submission to CodaLab. This isn't urgent, though, as we don't need a test set to do pretraining.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/418.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
