### ISSUE TITLE
Performance issue in QNLI test split (not val)

### ISSUE THREAD

**Issue by Iwontbecreative** [nyu-mll/jiant#432]
Hi,

We're doing GLUE runs using jiant. We're finding consistent performance losses (-6 to -10pts) when going from val to test on QNLI. Other tasks are fine. We thought it might be due to different test distribution, but both OpenAI GLUE scores and GLUE baselines seem to indicate that test set should be easier, not harder (they're seeing ~3 pts improvement).

Given the above, the issue is likely in Jiant's handling of the test set (we're replicating val results) and was not present in the GLUE baselines code. It also likely impacted Looking for ELMO's friends paper.

We've been trying to find the source of the bug but it's been hard to track down. Any idea/insights are welcome as this jeopardizes a bit the use of Jiant for GLUE.

**Comment by Iwontbecreative** [comment]
This is likely due to `BucketIterator`'s padding by length leading to pathological training on QNLI. Shuffling the data and switching to a `BasicIterator` seems to fix this issue. Will commit something / help on this later next week.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/432.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
