### ISSUE TITLE
Get rid of the two-phase structure in main.py

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#445]
Move the order of operations into the config file, rather than hardcoding a pretrain-train-eval pipeline. This should simplify things for anything resembling STILTs. 

(cc @zphang @Iwontbecreative )

**Comment by sleepinyourhat** [comment]
Yeah, I was figuring as much. Backwards compatibility doesn't seem like a priority at this point—we can fix any checked-in config files with the change, and it shouldn't be too painful to support the users we have so far.

**Comment by sleepinyourhat** [comment]
#557 should at least help.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/445.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
