### ISSUE TITLE
Automatically shard training data into multiple files

### ISSUE THREAD

**Issue by iftenney** [nyu-mll/jiant#449]
When writing serialized instances, write round-robin to sharded files.

This should (mostly) solve the shuffling issue described in #428 since we can read from the shards in random order, in addition to shuffling the input buffer. This should also result in better IO performance on large datasets due to parallel reads.

We can also process each shard in parallel during indexing for lower startup latency.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/449.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
