### ISSUE TITLE
Switch from HOCON to Jsonnet

### ISSUE THREAD

**Issue by iftenney** [nyu-mll/jiant#475]
AllenNLP did this recently: https://github.com/allenai/allennlp/releases/tag/v0.6.0 
https://jsonnet.org/ 

I haven't used Jsonnet yet, but HOCON is kinda wonky so this might be worth doing for our config system too.

**Comment by iftenney** [comment]
#852 and #853 implement this for Kubernetes configuration.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/475.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
