### ISSUE TITLE
Allow multiple evaluation/prediction sets for each task

### ISSUE THREAD

**Issue by iftenney** [nyu-mll/jiant#503]
Currently we allow exactly three sets: train, val, and test. There are a number of cases (NLI probing, diagnostics, etc.) where we want to train a single model and run several evaluations. Currently this is done by some hacky aliasing of tasks (having one task use the classifier for another). It might be cleaner to just allow a multiple (named) evaluations for the same task.

This would shift the Task abstraction from the current state of one-task-one-eval to one-task-one-classifier, which better aligns with the code.

**Comment by iftenney** [comment]
This would help with #502

**Comment by njjiang** [comment]
I'm trying to use the classifier of task X (MNLI) to evaluate task Y (other NLI *glue tasks). What is the current way of getting around this issue?

**Comment by njjiang** [comment]
Nevermind -- `use_classifier` in config seems to do it.

**Comment by sleepinyourhat** [comment]
Yep. The current workaround is to create a new task object that uses the same labels and the new test set, and set `[the_test_task_name] += {use_classifier = [the_main_training_task_name]}`.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/503.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
