### ISSUE TITLE
Support labeled data in inference script

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#508]
Add an option to run with labeled datasets (same format as would be used for a normal task dataset) and see accuracy/F1/MCC in addition to individual example labels.

@zphang @anhad13 – any interest?

**Comment by zphang** [comment]
This means inference + evaluation? 

Should this point to the specific train/dev.tsv rather than a full task folder? My thoughts are that this will piggy-back off the data-loading/metrics specific in the tasks.

**Comment by sleepinyourhat** [comment]
Not sure what you mean. The goal would be to make it easy to swap out the test/dev TSVs with new TSVs, and still have preprocessing etc. handled correctly. We can almost do that with the current inference executable, but it won't automatically do evaluation (right?).

**Comment by zphang** [comment]
Here's my plan:

- Additional argument for `input_format`: plain, train, dev, test (plain is just one sentence per line, train/dev/test will read in the corresponding format based on the `tasks.py` definition for that task - just CoLA for now)
- Additional argument for `eval_output_path` to optionally output a JSON with the metrics computed based on `tasks.py`, only works if `input_format`is `train` or `dev` (since only those two formats have labels)

**Comment by sleepinyourhat** [comment]
input_format: Sounds good.
eval_output_path: At least for now, it'd probably be reasonable to just write these to the end of the log or the end of the output file. Up to you, though.

**Comment by pruksmhc** [comment]
What's the status of this?
