### ISSUE TITLE
Make sure val_interval isn't too high.

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#537]
It's easy to accidentally do something like this:

max_epochs = 3
cola_val_interval = 100
pretrain_tasks = cola
target_tasks = cola
transfer_paradigm = finetune
do_pretrain = 1
do_target_task_training = 0
do_full_eval = 1
val_interval = 1000

Since we're treating our single task as a pretraining task rather than a target task, and not doing target_task_training, task-specific training options like cola_val_interval are ignored. So val_interval is set to 1000, even though an epoch of CoLA is only around 100 steps. This means that we actually train for >>3 epochs, since we only reach a stopping point to check the epoch count after it's too late.

Add an assert to make sure that val interval isn't too high when we're using max_epochs, or else add some code/language to push people to treat target tasks as target tasks, not as pretraining tasks.

**Comment by sleepinyourhat** [comment]
Spoiler: It's not an easy fix.

**Comment by sleepinyourhat** [comment]
Marking this low priority. Partially addressed by new comments in #596.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/537.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
