### ISSUE TITLE
Set up an example web demo for a jiant-trained model

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#552]
Easy-ish web demos are one of the major perks of sticking with AllenNLP. We should put together a brief guide on how to set them up.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/552.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
