### ISSUE TITLE
Create eval_tasks

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#569]
Since the previous usecase for jiant was to only evaluate on only target tasks, it is not possible right now to pretrain on task set A, target train on task set B, and then evaluate on set A in one run. 
The suggested solution is to have a separate eval_tasks list as well instead of always evaluating target_tasks list.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/569.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
