### ISSUE TITLE
Clean up Strict = False for loading models

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#573]
Right now, it's possible to load models that have missing model parameters and/or weights from a checkpoint (https://github.com/nyu-mll/jiant/blob/master/main.py#L272 and https://github.com/nyu-mll/jiant/blob/master/src/utils/utils.py#L79), which can be used when evaluating random classifiers. However, the logic behind this is quite messy - clear up when it's alright to have missing model parameters versus not.

**Comment by sleepinyourhat** [comment]
Still open after the recent refactor?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/573.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
