### ISSUE TITLE
Detach, data, cpu() in/around update_metrics

### ISSUE THREAD

**Issue by HaokunLiu** [nyu-mll/jiant#587]
The interface between forward function and update_metrics is somewhat messy across the code base, we might want to make it more organized

**Comment by sleepinyourhat** [comment]
PRs welcome if you see an easy improvement!

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/587.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
