### ISSUE TITLE
Set up real automatic enforcement of tests and style

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#619]
pep8speaks is slow/buggy, and doesn't enforce style, it just comments on it.

We don't have many tests, but we're even not using the ones we have reliably.

Set up a mechanism (Travis?) to enforce both.

**Comment by zphang** [comment]
I can help with this!

**Comment by sleepinyourhat** [comment]
Great! Go for it!

**Comment by zphang** [comment]
Doing some initial research/experimentation on this, here are some considerations:

### CI schedule

* I think it would be sufficient to just have this run on master, or potentially a small number of other candidate/release branches. This triggers on commit to the branch. 
* It's worth keeping in mind that because our environment uses a lot of libraries, it takes a while to set up the environment and run (installs/sets up the conda environment for each build). 

### Choice of CI platform

* There're a couple of options, which are somewhat more limited if we don't want to pay/host our own build machine. I'm currently looking at [CircleCI](https://circleci.com/product/), which provides [free](https://circleci.com/pricing/#build-linux) build Linux machines. MacOS build support is also available (paid). It does have a free build clock limit of 1000 minutes, which can be an issue if our environment is very slow to setup. 
* Note that once we get into the CI flow, it's not a *lot* of work to switch from one to another (except for the self-hosted solutions), so we can always choose to switch down the road.

@iftenney any thoughts?

**Comment by zphang** [comment]
For reference, this takes about 5 minutes for a build currently. Since our current tests are fairly trivial, almost all of that time is spent in environment setup. (The environmental setup time could still be slightly reduced/optimized.)

**Comment by sleepinyourhat** [comment]
Two quick thoughts:
- I'm open to paying a reasonable fee for machine time.
- We'd really want a mechanism to automatically check pending PRs against master, not just commits to master.

**Comment by zphang** [comment]
Follow discussion in: https://github.com/nyu-mll/jiant/pull/629

**Comment by sleepinyourhat** [comment]
CI is now added in #629, style checks pending.

**Comment by pruksmhc** [comment]
Seems to be done for now, can reopen if we end up running into any issues with CIrcleCI.

**Comment by sleepinyourhat** [comment]
Did the style checks ever get set up? The `black` thing isn't automatic for new contributors.

**Comment by zphang** [comment]
See: https://github.com/nyu-mll/jiant/pull/684
