### ISSUE TITLE
Make sure there's only one copy/URL for download_glue_data.py

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#633]
Alex:

> small thing, but previously this script was in a git gist, and that was the main version I updated. It'd be nice to have it in a single place, either this repo or a gist, so we don't have to maintain two versions.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/633.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
