### ISSUE TITLE
Move task specific prediction writing code to task objects

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#635]
Currently, we're piling each task's prediction writing code into `src/evaluate.py`, but these functions are probably better structured as task-object methods.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/635.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
