### ISSUE TITLE
Do another audit of our AllenNLP usage

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#657]
We did something like this a few months back, but it's worth taking another pass over our AllenNLP imports and major AllenNLP features with three questions in mind:

– Are there major methods from AllenNLP that are similar to ours that we can use? (Use them!)
– Do we have methods that build on AllenNLP in a way that fits nicely with their ecosystem? (Make PRs against Allen!)
– Are we using small AllenNLP helper methods that we could get rid of? (Get rid of them when this'd disconnect some major code paths from AllenNLP entirely—it'd probably simplify maintainance in those cases.)

**Comment by sleepinyourhat** [comment]
Probably a good idea for 1.0, but no urgent timeline.

**Comment by pruksmhc** [comment]
Bringing this up: the embedders in AllenNLP actually have some significant differences from our current set. For example, they implement the sliding window approach, which is crucial for implementations such as the ConNLL task. However, I now that our current implementation of the embedders also are more specific for probing. Would love input from @iftenney @sleepinyourhat @W4ngatang on how you think we should incorporate the AllenNLP embedders alongside the functionalities we want in the probing tasks.

**Comment by pruksmhc** [comment]
Also @HaokunLiu since you made the latest big change touching the embedders.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/657.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
