### ISSUE TITLE
CoVe doesn't work with BoW

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#677]
Using `bow` sentence encoder with CoVe will cause shape problems, because our BoW encoder doesn't compute CoVe embeddings. The correctness of this depends on whether you think BoW should allow for bag of contextual word embeddings, but at bare minimum we should probably have a config check for this and not allow it.

**Comment by sleepinyourhat** [comment]
Possible workaround: Set up the BERT arrangement as the standard way of using pretrained encoders. This'd mean adding a sum-pooling option, and making it clear that users should set sent_enc to none.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/677.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
