### ISSUE TITLE
Consider QHAdam

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#687]
This seems to be the Fancy New Optimizer Presented at ICLR for this year, with improvements over Adam: 

https://openreview.net/forum?id=S1fUpoR5FQ

I don't follow optimization closely, though, so there may be better alternatives out there, or reasons to doubt that these improvements will show up for what we're doing.

**Comment by sleepinyourhat** [comment]
Though here's a competing FNOPaI: https://openreview.net/forum?id=Bkg3g2R9FX

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/687.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
