### ISSUE TITLE
Make a tutorial on how to do transfer learning/MTL with another part of the model

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#695]
Instead of only doing transfer learning on the sentence encoder, we should have a tutorial on how to do transfer learning on another part of a model that's shared by tasks.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/695.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
