### ISSUE TITLE
Possible enhancement: Make checkpoints track which components were trained for what tasks

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#759]
This should simplify some of the hairier checkpointing logic:
- If we're evaluating, every parameter we touch should have been trained. Check that directly.
- If we're doing target task training, the shared encoder should have already been trained on the specified pretraining tasks. Check that directly.
- If we're doing target task training, the task-specific components should not have been trained yet. Check that directly.

There are other ways to do all of these things, but this could eventually get us to a more robust solution.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/759.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
