### ISSUE TITLE
Get rid of assert_for_log

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#769]
It's now just equivalent to assert—it had previously been necessary under an older/simpler logging setup.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/769.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
