### ISSUE TITLE
Add instructions to reproduce the Beyond Sesame Street paper

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#772]
The documentation (https://github.com/nyu-mll/jiant-site/blob/master/documentation/README.md) currently contains stale instructions for ELMo's Friends.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/772.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
