### ISSUE TITLE
Parameters for sequence generation, LM tasks won't fine-tune.

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#81]
This is not really an issue if we're only fine-tuning on GLUE tasks but

At fine-tuning time, we get the parameters to fine-tune by finding model attribute `(%s_mdl) % task.name` but for several types of tasks, the attributes to be trained are set with different names, e.g. `%s_decoder`.

Suggested solution, wrap components in an `nn.Module` to easily get parameters.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/81.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
