### ISSUE TITLE
Add Macro/Micro to Tensorboard

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#814]
Currently, we are not logging macro/micro averages on Tensorboard since it was appearing strangely in the interface (picture below), so it was removed. 

![Screenshot 2019-07-04 15 06 45](https://user-images.githubusercontent.com/10094008/60774309-98e87380-a0e0-11e9-9f03-b04f9c614df2.jpg)

Add macro/micro to Tensorboard.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/814.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
