### ISSUE TITLE
Creating full vocabulary when not needed

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#819]
Running the with the SuperGLUE BERT config at head, I see this in the logs:

```
07/08 04:37:25 PM: 	Building vocab from scratch.
07/08 04:37:25 PM: 	Counting words for task rte.
07/08 04:37:25 PM: 	Counting words for task rte-superglue.
07/08 04:37:25 PM: loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-cased-vocab.txt from cache at /Users/Bowman/.pytorch_pretrained_bert/cee054f6aafe5e2cf816d2228704e326446785f940f5451a5b26033516a4ac3d.e13dbb970cb325137104fb2e5f36fe865f27746c6b526f6352861b1980eb80b1
07/08 04:37:26 PM: BERT WPM vocab (model=bert-large-cased): 28996 tokens
07/08 04:37:26 PM: 	Saved vocab to /Users/Bowman/Drive/JSALT/bert-large-cased/vocab
07/08 04:37:26 PM: Loading token dictionary from /Users/Bowman/Drive/JSALT/bert-large-cased/vocab.
07/08 04:37:26 PM: 	Loaded vocab from /Users/Bowman/Drive/JSALT/bert-large-cased/vocab
07/08 04:37:26 PM: 	Vocab namespace chars: size 106
07/08 04:37:26 PM: 	Vocab namespace tokens: size 15135
07/08 04:37:26 PM: 	Vocab namespace bert-large-cased: size 28998
```

The first and last few lines show that the model is creating a character and word vocabulary, even though we're using BERT with no decoder, so the only relevant vocabulary is the BERT WordPiece vocabulary. This doesn't add much time in standard runs, but it may be indicative of a bigger problem, so it's worth a look.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/819.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
