### ISSUE TITLE
Misleading warning with BERT `No shared encoder (just using word embeddings)!`

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#820]
I get the log message `No shared encoder (just using word embeddings)!` when using the BERT SuperGLUE config. This is presumably incorrect/misleading, since all tasks share the BERT encoder. We should probably just delete this message.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/820.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
