### ISSUE TITLE
Don't save model + training state on GPU

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#828]
Currently we're saving model states on GPU, so if you load that model state on a different GPU (id) later, it will error.

**Comment by W4ngatang** [comment]
Hmm , this should be handled in `load_model_state`, but I still get errors. Will look into later.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/828.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
