### ISSUE TITLE
Throw an error on misspelled arg names

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#839]

**Comment by sleepinyourhat** [comment]
More than I can take on, but here's a sketch:

- Merge select_relevant_print_args and check_configurations, either in main.py or config.py.
- Existing code in will get you a list of all the parameters specified in defaults.conf.
- Iterate over args, and assert that every arg either (i) appears in defaults.conf or (ii) matches a task name, and is an arg dict (like `mnli` in `mnli = {lr = 1.0}`) rather than a single terminal arg.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/839.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
