### ISSUE TITLE
Prevent LR decay during warmup

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#847]
When using `bert_adam`, it's currently possible that `lr_patience` will kick in and lower the learning rate before warmup is done, which doesn't seem well-motivated. Let's prevent that from happening until we've been out of the warmup phase for at least `lr_patience` validations. 

Relevant: 

https://twitter.com/davis_yoshida/status/1151557784003055616

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/847.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
