### ISSUE TITLE
Early crashes are not logged

### ISSUE THREAD

**Issue by iftenney** [nyu-mll/jiant#856]
If main.py crashes before running `initial_setup()` - for example, when validating configs - the experiment directory is never created and no logfile is written. This is not a big deal if starting jobs one-by-one from a local shell, but leads to silent failure if running a set of jobs on a cluster.

Proposed fix: create working directories and initialize log handlers before validating remaining arguments.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/856.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
