### ISSUE TITLE
Remove unused legacy code for task-specific optimizers

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#869]

**Comment by HaokunLiu** [comment]
which code are you referring to?

**Comment by sleepinyourhat** [comment]
We used to have a partially-supported option to maintain a separate optimizer object for each task in MTL. I can't tell where this was removed, but it was, in fact, removed.

There is still one stale comment about it that should be removed, though:
https://github.com/nyu-mll/jiant/blob/master/jiant/trainer.py#L299

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/869.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
