### ISSUE TITLE
Set up Apex in Docker

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#870]
I've had a bit of luck experimenting with NVIDIA Apex locally—it promises to offer speedups from half-precision training—but I haven't found a way to get it to build in the same Dockerfile as everything else. Is anyone with more managing-complex-Linux-dependencies experience interested?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/870.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
