### ISSUE TITLE
Clarify the distinction between 'bow' and 'none' for sent_enc

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#874]
I'm not sure I see use cases for both. @W4ngatang, @pruksmhc, @iftenney - Have any of you ever seen a use case that's specific to one but not the other?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/874.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
