### ISSUE TITLE
Check configs earlier

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#883]
Much of the logic in check_configurations in main can be checked before we do the expensive step of loading tasks. Moving this earlier in main should save a good deal of time that would be otherwise wasted loading tasks under inconsistent configs.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/883.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
