### ISSUE TITLE
CircleCI tests run even on documentation-only PRs

### ISSUE THREAD

**Issue by iftenney** [nyu-mll/jiant#894]
It seems a bit silly to run demo.conf when you only edited some markdown.
Is there a way to selectively run depending on what files are changed?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/894.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
