### ISSUE TITLE
Change default val_interval for the GLUE tasks

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#905]
I have noticed for some of the tasks (specifically MNLI that i have tested in the past few days), the convergence and performance depends on val_interval. If val_interval is small, then especially if patience is small, there might not be that much difference in performance every validation step, thus the training process will stop before significant performance gains can be gained. 
We should change the default val_intervals or make that more clear in the docs so that people know that is a place to look if they're not getting as high of a performance number as reported.

**Comment by HaokunLiu** [comment]
Yes, I also noticed that. It gets even worst with the exponential lr decay in jiant (comparing to linear in the papers). When the model didn't get performance gain due to insufficient movement, the lr shrinks so quickly, make it harder for the parameters to move long enough.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/905.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
