### ISSUE TITLE
Expose intermediate repr, attention weight, and other meaningful tensors

### ISSUE THREAD

**Issue by HaokunLiu** [nyu-mll/jiant#910]
We may want to save some tensors in the model to a file, for further study. This is needed for some error analysis, and many other analysis methods.
Yet there are a few things we need to think through.

Saving either the entire computation graph, or over the full training process, or in some extreme cases, over full dataset, will consume crazy amount of storage. So we need some way to flexibly select parts we are interested with on all the three sides.

If a user can select them in config file, without the need to modify the code, that would the most desirable.

I don't clearly know how should we design it, especially the computation graph part.

**Comment by sleepinyourhat** [comment]
I'm open to good ideas here, but I think the lazy default is simply to take advantage of what makes PyTorch so distinctively useful: It's easy to load a trained model from disk, insert print/save code in the model, then run it.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/910.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
