### ISSUE TITLE
Transient failures when starting many jobs in the same exp_dir

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#911]
When starting a new experiment it's common to launch several runs at once that need the same data. This will create a race as the jobs all try to write and read the same preprocessed data at once, and it seems like this isn't always handled well. It's always the case that most of the jobs will survive, but often a fraction will fail with a variety of data loading issues. 

The most recent one I've seen is this, happening to about 15% of jobs that use a given set of tasks:

```
09/09 07:48:08 PM: Number of trainable parameters: 355375115 (3.55375e+08)
09/09 07:48:08 PM: Finished building model in 16.717s
09/09 07:48:08 PM: Will run the following steps for this experiment:
Training model on tasks: mnli 
Re-training model for individual target tasks 
Evaluating model on tasks: boolq,multirc,rte-superglue,wic 

09/09 07:48:08 PM: Training...
09/09 07:48:08 PM: patience = 100000
09/09 07:48:08 PM: val_interval = 5000
09/09 07:48:08 PM: max_vals = 100000
09/09 07:48:08 PM: cuda_device = 0
09/09 07:48:08 PM: grad_norm = 5.0
09/09 07:48:08 PM: grad_clipping = None
09/09 07:48:08 PM: lr_decay = 0.99
09/09 07:48:08 PM: min_lr = 1e-07
09/09 07:48:08 PM: keep_all_checkpoints = 0
09/09 07:48:08 PM: val_data_limit = 5000
09/09 07:48:08 PM: max_epochs = 4
09/09 07:48:08 PM: dec_val_scale = 250
09/09 07:48:08 PM: training_data_fraction = 1
09/09 07:48:08 PM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    main(sys.argv[1:])
  File "jiant/__main__.py", line 540, in main
    phase="pretrain",
  File "jiant/trainer.py", line 495, in train
    tasks, batch_size, train_params, optimizer_params, scheduler_params, phase
  File "jiant/trainer.py", line 316, in _setup_training
    instance = [i for i in itertools.islice(task.train_data, 1)][0]
IndexError: list index out of range
```

**Comment by W4ngatang** [comment]
Yea, this is annoying. Not sure what's a reasonable solution, though. AFAIK
there's not a way to tell if another process is reading a file or to put a
lock on it. Maybe make a copy of the pickle and read from that instead ?

**Comment by pyeres** [comment]
Hey, my understanding is that file locking is generally difficult (e.g., [On the Brokenness of File Locking](http://0pointer.de/blog/projects/locking.html)), but if the files are private (permissioned ["at most `0600`"](https://stackoverflow.com/questions/28470246/python-lockf-and-flock-behaviour#comment73298350_34935188)), packages like [filelock](https://pypi.org/project/filelock/) can help us manage concurrent access without errors like the above. Planning to discuss with @pruksmhc and @HaokunLiu.

**Comment by HaokunLiu** [comment]
On second thought, there maybe a "homemade" solution.

If we have our program executing the following steps, whenever creating cache files (assume it's called "cache.pkg").
0. check if "cache.pkg" exist, if yes, load that file, and skip all following steps.
1. process the data in memory until ready to make cache.
2. create a cache file unique to the process (assume it's called "cache_1L4KAHREH65A.pkg"), based on some hashing, save data to that file. 
3. try to rename "cache_1L4KAHREH65A.pkg" to "cache.pkg"
4. if (3) fails, delete its unique cache "cache_1L4KAHREH65A.pkg".

First, we know the data is correct. If 0 is successful, that means "cache.pkg" is completely created by another process and then renamed. So it's safe to load. If 0 fails, no matter what happened to 2,3,4. The data is generated anew, so it's safe.

Second, we know the program can't crash because of conflict. The only place conflicts can happen is 3, and we already have 4 to handle that.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/911.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
