### ISSUE TITLE
Character Embedding

### ISSUE THREAD

**Issue by ppriyank** [nyu-mll/jiant#914]
If I want to use character embedding in addition to word embeddings, 

When I add the following to conf file
`input_module = elmo`
`char_embs = 1`

I get the error : 

**allennlp.common.checks.ConfigurationError: "Mismatched token keys: dict_keys(['chars', 'elmo']) and dict_keys(['elmo'])"**

The error is due to the line in `__main__.py`: 

```trainer, ...  = build_trainer( ... )```
```trainer.train()```

Should I manually change the model code or something?

**Comment by sleepinyourhat** [comment]
Bad news: No one has been using the dedicated character embedding code recently, AFAIK, and they were added before we added most of our tests, so it's possible that support is partially broken. If you want to use it and you see an easy change, I'd encourage you to make a PR.

FWIW, though, we definitely do have working support for ELMo's pretrained character encoder. There's an option to use the full ELMo, and another option to use only the character layer from ELMo.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/914.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
