### ISSUE TITLE
Allow data_fraction args to be set for specific tasks

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#917]
Ideally, we'd support something like `mnli += {pretrain_data_fraction = 0.5}, pretrain_tasks = {mnli,boolq}`. Currently, pretrain_data_fraction is just a global argument for all pretraining tasks.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/917.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
