### ISSUE TITLE
Add ability to reload tasks without reloading data 

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#930]
Sometimes, we need to change only a scorer or a task attribute, but reload_tasks=1 means load_data() is also called. This is unnecessarily time-consuming.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/930.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
