### ISSUE TITLE
[Feature request] Make it easier to load a model other than from pytorch-huggingface

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#933]
If there is another BERT-based model (such as clinicalBERT) that is currently not part of huggingface, it is very hard to add it. We should make the code more generalizable (for example, the current way we build vocabulary is quite specific to huggingface).

**Comment by sleepinyourhat** [comment]
Quickly: In that case, why not just make a PR to Huggingface?

**Comment by pruksmhc** [comment]
Because that would require understanding a second (and much larger) repo :S. I don't think this change will be too big, the tricky parts would be in handling vocab and making sure we allow input_module to be a path to a model as well as the current options.

**Comment by sleepinyourhat** [comment]
I'm still nervous. The Huggingface repo/team has thought pretty hard about how to do this well, and I can imagine a lot of things we could get wrong if we don't prioritize this. I'd vote fairly strongly against doing this for anything that's within the reasonable scope of the Huggingface repo.

(For smaller/simpler models without checkpoints/special tokenizers/special optimizers, this shouldn't really be an issue.)

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/933.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
