### ISSUE TITLE
Edge probing data stats don't match

### ISSUE THREAD

**Issue by shtoshni92** [nyu-mll/jiant#936]
Hi guys,

I'm working on the edge probing task and I used the [edge_data_stats](https://github.com/nyu-mll/jiant/blob/master/probing/edge_data_stats.py) script to verify the data stats. Interestingly, while the total number of tokens and instances are matching the stats presented in Appendix B of [the paper](https://arxiv.org/pdf/1905.06316.pdf), the total targets number is significantly off. So for ontonotes-coref's train split, I get the target count to be 207830 or ~208K which is almost 40K from the 248K number reported in the paper. Similarly, this target count stat is off for the development and test part as well. I also checked the stats for const (constituency) and that seems to be quite off as well. Any idea as to why this might be happening. Also, is it possible for you guys to double-check these numbers. 

Thanks,
Shubham

**Comment by sleepinyourhat** [comment]
@iftenney, any guesses?

**Comment by iftenney** [comment]
@pitrack can you confirm how you calculated the numbers in the table?

**Comment by pitrack** [comment]
Thanks for bringing this up. There are a couple errors in the data table. Here is what I found:

1. POS is correct
2. Constituents are correct
3. Dependencies are correct
4. Entities are correct. 
5. SRL train/dev are correct. Test* should be 26715 examples, 711746 tokens, and 61716 targets.
   a. ... of which 41735 are core roles targets
   b. ... of which 18290 are non-core role targets
6. In Coreference, the targets should be **207830/26333/27800**, which looks like what you're getting.
7. In SPR1, there are **518** dev examples, not 513. 
8. In SPR2, the token counts should be 47K/**5.6K/4.9K** (specifically 5592/4929)
9. For Winograd, there are 958/223/518 examples, 14K/**4.3K/8.0K** tokens (specifically 14384/4331/7952), and 1787/**379/949** targets
10. I am currently unable to verify Relations, though a quick glance suggests something might be a bit off, since 85%/15% of 8000 training examples is 6.8K/1.2K, not 6.9K/1.1K.

\* Originally reported  SRL test stats were on the conll-2012 test set, but all OntoNotes-derived data for this paper are split according to the official train/dev/test sets.

I apologize for the errors in this table; I should have double-checked them on the final version of the data that we used in our final draft.

What numbers are you getting for constituents/part-of-speech? For `const/*.json`, you should be getting 3.9M/545K/403K targets but this includes both Part-of-Speech (terminals) and Constituents (non-terminals). When split using [split_constituent_data.py](https://github.com/nyu-mll/jiant/blob/master/probing/split_constituent_data.py), you should be getting the numbers in the table.

**Comment by shtoshni92** [comment]
Thanks for the quick check!
Currently, we're only focussing on coreference and constituency but it's good to know the corrected stats as well.
Right now we're only working on the coreference & constituent task. The numbers for coreference are exactly match up :)
For constituent, the numbers are indeed matching after splitting the data using the split script. 
BTW regarding the model performances reported on the constituent task, are the reported numbers just on the non-terminals or include terminals as well?

**Comment by pitrack** [comment]
Since we split up the "consts" data into non-terminals ("Constituents") and terminals ("Part of Speech"), the number reported for "Constituents" is just the non-terminals

**Comment by sleepinyourhat** [comment]
Thanks @pitrack – would you mind putting together a readme somewhere with these updated numbers?
