### ISSUE TITLE
setup tutorial typo

### ISSUE THREAD

**Issue by antgr** [nyu-mll/jiant#938]
``` run_name, which expects a string of your run name. The main differences between an experiment and a run is that all runs in an experiment will have the same preprocessing (which may include tokenization differences),``` ** while runs his a specific experiment ** ```(which may differ from other runs by learning rate or type of sentence encoder, for example, your run name could be rnn_encoder for a run with a biLSTM sentence encoder). ```
I think that there is a typo there

**Comment by sleepinyourhat** [comment]
Thanks! @pruksmhc - Do you have any bandwidth to edit?

**Comment by sleepinyourhat** [comment]
(@antgr - If you've figured out the intent, feel free to make a PR!)

**Comment by pruksmhc** [comment]
Yep! I'll get to this later today.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/938.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
