### ISSUE TITLE
Adding ability to handle documents of >512 tokens

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#940]
RIght now, we don't have any sliding window based approach for handling longer documents for models such as BERT. This is in fact integrated within AllenNLP's BertTokenEmbedder and BertIndexer (and the like for other BERT variants), which we do not currently use in jiant. 
This also has to do with revisiting our relationship with AllenNLP https://github.com/nyu-mll/jiant/issues/657.

**Comment by sleepinyourhat** [comment]
Still high-priority after recent discussion?

**Comment by pruksmhc** [comment]
I'm claiming this.

**Comment by sleepinyourhat** [comment]
Neat!

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/940.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
