### ISSUE TITLE
Multitask learning for Sequence Labeling Task

### ISSUE THREAD

**Issue by antgr** [nyu-mll/jiant#962]
Hi,
I would like to apply multitask learning, for two tasks, one of which is a Sequence Labeling Task.
If this information clarifies the things better, the other task could be a NLI task. 
Do you have an example of how I could create a proof of concept for that goal?
Thanks!

**Comment by antgr** [comment]
A kind reminder!

**Comment by antgr** [comment]
@pruksmhc Any thoughts on that?

**Comment by antgr** [comment]
@sleepinyourhat Prof, any feedback on that?

**Comment by pruksmhc** [comment]
Hi! Sorry for the delay, we do have a task called TaggingTask in jiant/models.py (look at CCG task for reference of how to implement a sequence labelling task), as well as an NLI task (look at MNLI or any of the other NLI task for example). I would suggest following the tutorial on how to do multitask learning between the two tasks.

**Comment by antgr** [comment]
Thanks! Because the data for CCG need licence, I cannot try it and start from there (Although I could follow the code). But the main issue for me, is what data format is expected? Json? tsv? For ccg I need to run a script like ./scripts/ccg/ccg_proc.py, which transforms data to a desire format. Could you  elaborate e.g for NER case? And then I think that I can find my way for my dataset as well.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/962.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
