### ISSUE TITLE
TokenIndexers with vocab broken for ELMo + biLSTM 

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#963]
Somewhere between the July 1st release and now, token indexing became out of sync with vocab for non-pytorch huggingface code. Most importantly, the way we're handling indexer names works for pytorch huggingface, but does not work for indexing. This also points to the fact that we do not have testing for maintaining state between token indexer and vocab names. I will elaborate more in a few days when I have more time.
@HaokunLiu  @pyeres

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/963.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
