### ISSUE TITLE
Add hyperparameter tuning 

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#964]
Add a feature to automatically do hyperparameter tuning. 
This seems useful:
https://github.com/ChristophAlt/tuna

**Comment by sleepinyourhat** [comment]
Related: Is ASAPP's tool for this maintained (or any good)?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/964.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
