### ISSUE TITLE
Question: Why both load_eval_checkpoint and load_target_train_checkpoint?

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#973]
I think we may have worked our way into a bit of redundancy through historical accident: We have two flags that specify checkpoints to load upon launch.

They're loaded in different parts of the code, but in practice, I think you can always derive that decision from the other flags (if do_target_task_train, then check load_target_train_checkpoint). Is there a reason we shouldn't just merge them?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/973.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
