### ISSUE TITLE
Increase test coverage over training code

### ISSUE THREAD

**Issue by pyeres** [nyu-mll/jiant#983]
Changes like #980 would be safer and faster with improved test coverage. This issue requests more test coverage over the core training classes.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/983.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
