### ISSUE TITLE
Move CCG and Edge probing preprocessing code into their Task classes

### ISSUE THREAD

**Issue by HaokunLiu** [nyu-mll/jiant#995]
Right now, CCG and Edgeprobing both have some preprocessing code scattered around (/scripts/ccg/align_tags_to_bert.py , /probing/retokenize_edge_data). Those code are less well documented and maintained. But their functionality is actually no different from Task.process_split, i.e. tokenizing the sentences and aligning token indexes. Whenever a new transformer model comes out, we need to run those code again to get the tokenized data, before running the main jiant program.

If we can move them into their corresponding Task classes (I mean make a version similar other tasks, not directly copy&paste) , this will save us a lot of troubles later on.

**Comment by HaokunLiu** [comment]
#871

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/995.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
